### ISSUE TITLE
Feature Request: Only check for updates on a schedule

### ISSUE THREAD

**Issue by elpete** [commandbox-modules/commandbox-update-check#1]
As a Mac user, I only enter in to CommandBox when needed.  This means the Update Check module checks multiple times throughout the day.

I think it would be nice to only check once a week, like with ZSH.  This could be configurable as well.

**Comment by bdw429s** [comment]
I asked this feature last week. Did I not push and bump it or have you just not tried the latest version?

**Comment by elpete** [comment]
I didn't see anything in the documentation.  How do you set it up?

**Comment by bdw429s** [comment]
It's implemented here:
https://github.com/commandbox-modules/commandbox-update-check/blob/master/ModuleConfig.cfc#L25
and here:
https://github.com/commandbox-modules/commandbox-update-check/blob/master/ModuleConfig.cfc#L50

I didn't add anything to the docs partly because I'm lazy and partly because it wasn't really intended to be configurable yet.  Right now it checks once a day.  If you run this, you can see when it last checked:
```
config show modules.commandbox-update-check.dateLastChecked
```
